language: csharp
dist: xenial
solution: TTExecuter.Master.sln
script:
    - nuget restore
    - dotnet restore
    - dotnet build
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1